[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --no-input"
]

[start]
cmd = "gunicorn carmarket.wsgi:application --bind 0.0.0.0:$PORT"
